/**
 * Shadow Engineering - Observer Agent
 *
 * Watches team's development work and provides assistance.
 * Default mode: Watch-only (comments on PRs with observations).
 * Propose mode: Requires explicit `/shadow propose` command to create PRs.
 *
 * Monitors PR activity (polls initially), comments with observations,
 * tracks progress against Inference Document, flags deviations.
 */

import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { Data, Effect } from 'effect';
import { readInferenceDocumentSync } from './monitoring-agent.js';

const execAsync = promisify(exec);

export interface ObserverAgentConfig {
  issueId: string;
  workspacePath: string;
  projectPath: string;
  repo: string; // owner/repo format
  mode: 'watch' | 'propose';
}

export interface PRInfo {
  number: number;
  title: string;
  author: string;
  branch: string;
  state: string;
  body: string;
  additions: number;
  deletions: number;
  changedFiles: number;
  comments: Array<{ author: string; body: string; createdAt: string }>;
}async function pollPRsPromise(config: ObserverAgentConfig): Promise<PRInfo[]> {
  const prs: PRInfo[] = [];

  try {
    // Search for PRs mentioning the issue ID
    const { stdout } = await execAsync(
      `gh pr list --repo ${config.repo} --search "${config.issueId}" --json number,title,author,headRefName,state,body,additions,deletions,changedFiles,comments --limit 10`,
      { encoding: 'utf-8', timeout: 30000 }
    );

    const parsed = JSON.parse(stdout || '[]');
    for (const pr of parsed) {
      prs.push({
        number: pr.number,
        title: pr.title,
        author: pr.author?.login || 'unknown',
        branch: pr.headRefName,
        state: pr.state,
        body: pr.body || '',
        additions: pr.additions || 0,
        deletions: pr.deletions || 0,
        changedFiles: pr.changedFiles || 0,
        comments: (pr.comments || []).map((c: any) => ({
          author: c.author?.login || 'unknown',
          body: c.body,
          createdAt: c.createdAt,
        })),
      });
    }
  } catch (err: any) {
    console.warn(`Observer: Failed to poll PRs for ${config.issueId}:`, err.message);
  }

  return prs;
}

/**
 * Generate an observation for a PR
 */
export function generateObservation(
  pr: PRInfo,
  inference: string | null,
  config: ObserverAgentConfig
): string | null {
  // Skip if we've already commented (check for our marker)
  const hasOurComment = pr.comments.some(c =>
    c.body.includes('[Shadow Engineering Observer]')
  );
  if (hasOurComment) return null;

  const sections: string[] = [];
  sections.push(`### [Shadow Engineering Observer] - Observations for #${pr.number}`);
  sections.push('');

  // Basic observations
  sections.push(`**PR Summary**: ${pr.title}`);
  sections.push(`**Changes**: +${pr.additions}/-${pr.deletions} across ${pr.changedFiles} file(s)`);
  sections.push('');

  if (inference) {
    sections.push(`**Alignment with Inference Document**: This PR appears to contribute to the documented plan.`);
    sections.push('');
  }

  // Size-based observation
  if (pr.additions + pr.deletions > 500) {
    sections.push(`> **Note**: This is a large PR (${pr.additions + pr.deletions} lines changed). Consider splitting into smaller reviews for easier review.`);
    sections.push('');
  }

  if (pr.changedFiles > 20) {
    sections.push(`> **Note**: This PR touches ${pr.changedFiles} files. Ensure adequate test coverage for all changed modules.`);
    sections.push('');
  }

  sections.push('---');
  sections.push('*This observation was generated by the Shadow Engineering Observer Agent in watch-only mode.*');

  return sections.join('\n');
}async function postPRCommentPromise(
  repo: string,
  prNumber: number,
  comment: string
): Promise<boolean> {
  try {
    await execAsync(
      `gh pr comment ${prNumber} --repo ${repo} --body "${comment.replace(/"/g, '\\"')}"`,
      { encoding: 'utf-8', timeout: 15000 }
    );
    return true;
  } catch (err: any) {
    console.warn(`Observer: Failed to comment on PR #${prNumber}:`, err.message);
    return false;
  }
}

/**
 * Generate the observer prompt for the Observer Agent
 */
export function generateObserverPrompt(
  config: ObserverAgentConfig,
  prs: PRInfo[],
  inference: string | null
): string {
  const sections: string[] = [];

  sections.push(`# Shadow Engineering - Observer Task`);
  sections.push(`\nYou are the Shadow Engineering Observer Agent for ${config.issueId}.`);
  sections.push(`Mode: ${config.mode === 'watch' ? 'WATCH-ONLY (comment only, no changes)' : 'PROPOSE (can create PRs when asked)'}`);

  if (config.mode === 'watch') {
    sections.push(`\n**IMPORTANT**: You are in watch-only mode. You may ONLY:`);
    sections.push(`- Comment on PRs with observations, suggestions, and potential issues`);
    sections.push(`- Track progress against the Inference Document`);
    sections.push(`- Flag deviations or scope changes`);
    sections.push(`- Document patterns the team is using`);
    sections.push(`\nYou may NOT create PRs, push code, or make changes.`);
  }

  if (inference) {
    sections.push(`\n## Inference Document\n\n${inference}`);
  }

  if (prs.length > 0) {
    sections.push(`\n## Active PRs\n`);
    for (const pr of prs) {
      sections.push(`### PR #${pr.number}: ${pr.title}`);
      sections.push(`- Author: ${pr.author}`);
      sections.push(`- Branch: ${pr.branch}`);
      sections.push(`- Changes: +${pr.additions}/-${pr.deletions} (${pr.changedFiles} files)`);
      if (pr.body) sections.push(`- Description: ${pr.body.slice(0, 300)}`);
      sections.push('');
    }
  } else {
    sections.push(`\n## Active PRs\n\nNo PRs found for ${config.issueId}.`);
  }

  sections.push(`\n## Your Task`);
  if (config.mode === 'watch') {
    sections.push(`Review the PRs above and provide helpful observations.`);
    sections.push(`Focus on: code quality, alignment with the inference document, potential issues, and helpful suggestions.`);
  } else {
    sections.push(`Review the PRs above. You have been asked to propose changes.`);
    sections.push(`Create focused, well-tested PRs that address specific gaps identified in the Inference Document.`);
  }

  return sections.join('\n');
}async function runObserverCyclePromise(config: ObserverAgentConfig): Promise<number> {
  const inference = readInferenceDocumentSync(config.workspacePath);
  const prs = await Effect.runPromise(pollPRs(config));

  let commentsPosted = 0;

  for (const pr of prs) {
    const observation = generateObservation(pr, inference, config);
    if (observation) {
      const posted = await Effect.runPromise(postPRComment(config.repo, pr.number, observation));
      if (posted) commentsPosted++;
    }
  }

  return commentsPosted;
}

// ─── Effect variants (PAN-1249) ───────────────────────────────────────────────
//
// Wraps the gh-CLI-backed observer I/O (pollPRs, postPRComment, runObserverCycle)
// in typed Effect channels. The underlying functions already swallow most
// errors and return defaults, so the Effect variants only surface truly
// thrown exceptions (e.g. JSON parse failures, gh missing).

/** Tagged error for observer-agent Effect variants. */
export class ObserverAgentError extends Data.TaggedError('ObserverAgentError')<{
  readonly issueId: string;
  readonly operation: string;
  readonly message: string;
  readonly cause?: unknown;
}> {}

const liftObserverError = (
  issueId: string,
  operation: string,
  cause: unknown,
): ObserverAgentError =>
  new ObserverAgentError({
    issueId,
    operation,
    message: cause instanceof Error ? cause.message : String(cause),
    cause,
  });

/** Effect variant of `pollPRs`. */
export const pollPRs = (
  config: ObserverAgentConfig,
): Effect.Effect<PRInfo[], ObserverAgentError> =>
  Effect.tryPromise({
    try: () => pollPRsPromise(config),
    catch: (cause) => liftObserverError(config.issueId, 'pollPRs', cause),
  });

/** Effect variant of `postPRComment`. */
export const postPRComment = (
  repo: string,
  prNumber: number,
  comment: string,
): Effect.Effect<boolean, ObserverAgentError> =>
  Effect.tryPromise({
    try: () => postPRCommentPromise(repo, prNumber, comment),
    catch: (cause) => liftObserverError(`${repo}#${prNumber}`, 'postPRComment', cause),
  });

/** Effect variant of `runObserverCycle`. */
export const runObserverCycle = (
  config: ObserverAgentConfig,
): Effect.Effect<number, ObserverAgentError> =>
  Effect.tryPromise({
    try: () => runObserverCyclePromise(config),
    catch: (cause) => liftObserverError(config.issueId, 'runObserverCycle', cause),
  });
